### ISSUE TITLE
maxTime in NEST Kr83m model

### ISSUE THREAD

**Issue by HenningSE** [XENONnT/epix#29]
In epix we set `A` and `Z` to zero in case they are not explicitly needed by e.g. the NEST Ion model. Inside NEST, `A` and `Z` are the variables `massNum` and `atomNum`. These variables are only explicitly used in the Ion model: https://github.com/NESTCollaboration/nest/blob/master/src/NEST.cpp#L718 or the NR model: https://github.com/NESTCollaboration/nest/blob/master/src/NEST.cpp#L713. 

For some reason `massNum` is used as placeholder for a variable `maxTimeSeparation` when using the Kr83m model: https://github.com/NESTCollaboration/nest/blob/master/src/NEST.cpp#L723-L725. When `A` is set to `0` in epix the NEST Kr83m call freezes. 

- Can we just set `A` to an value other than 0?
- Do we need to calculate a proper time separation?

**Comment by sophiaandaloro** [comment]
Hey @HenningSE, yeah I’ve noticed that too it is super confusing to use the MassNum in place of the time separation for krypton. I guess it is to use the GetYields function ubiquitously, for all interactions-- on the NEST side. But that is annoying for your use case. In the case where A and Z are not needed, could we set them to infinity instead and that would take care of the freeze? 
The freeze is occurring because of this line, where this is always true while A (maxTimeSeparation) is 0: https://github.com/NESTCollaboration/nest/blob/7c311e0b2d7d34fd75b2245d1f5b7a7780409862/src/NEST.cpp#L548
Additionally, could you point to where in epix you set to zero so I can see what our options are?

**Comment by HenningSE** [comment]
Hi @sophiaandaloro, thanks for checking. In epix A and Z are set when the clusters are classified: https://github.com/XENONnT/epix/blob/master/epix/clustering.py#L228-L271

**Comment by sophiaandaloro** [comment]
Ah yup, so I'd say when you can get a chance to, set to infinity (or even just the max time separation if you have a specific number in mind for that,) and test it out. Thanks !

**Comment by ramirezdiego** [comment]
Solved in https://github.com/XENONnT/epix/pull/30, thank you @sophiafarrell and @HenningSE!
